package abi;

import gson.GsonAbi;

import java.util.ArrayList;

/**
 * Class to represent a complete ABI generated by Solidity compiler
 */
public class Abi {
    private final ArrayList<AbiFunction> functions;

    /**
     * Builds an empty ABI
     */
    public Abi() {
        this.functions = new ArrayList<>();
    }

    /**
     * Adds a function to the ABI
     * @param function function to add
     */
    public void addFunction(AbiFunction function) {
        functions.add(function);
    }

    /**
     * Gets the functions
     * @return An iterable object with the functions
     */
    public Iterable<? extends AbiFunction> getFunctions() {
        return functions;
    }

    /**
     * Static method to build an ABI from a json file generated by Solidity compiler
     * @param src string representing the Json source
     * @return the built ABI
     */
    public static Abi fromJson(String src){
        return new GsonAbi().fromJson(src, Abi.class);
    }
}
